# Linear Discriminant Analysis

When there are more than 2 classes a better approach to classify them is to use LDA

why do do we need another method?

problems with logistic regression 

a) unstable when the classes are well separated

There are two different approches to do LDA, the one approach showed below is the Bayesian approach which assumes that the data within each class is normally distributed, the other approach is Fisher LDA 

https://stats.stackexchange.com/questions/87975/bayesian-and-fishers-approaches-to-linear-discriminant-analysis

###### the key Assumption

data for each class is normally distributed and 

in order to run the LDA we want the classes to have same variance

https://stats.stackexchange.com/questions/71489/three-versions-of-discriminant-analysis-differences-and-how-to-use-them

given the data we find what is probability that the data belongs to kth class 

$$P_r(Y = k|X = x) = \frac{\pi_k * f_k(x)} {\sum_{n=1}^{K} \pi_l * f_l(x)}$$

we know the prior probability and that the data within is normally distributed which is described by a PDF, using this in a Bayes theorem we get the posterior 

Given an observation, we will calculate the probability, that the observation belongs to one of the classes and then assign the class which has the highest probabiltity 

###### LDA and PCA are related, so before doing LDA it is better to learn the PCA and the implementation.
The implemetation of LDA is mostly the fisher LDA, which requires the principal components.

##### why LDA may overfit

https://stats.stackexchange.com/questions/108928/is-linear-discriminant-analysis-lda-more-likely-to-overfit-than-support-vector

https://stats.stackexchange.com/questions/306526/why-linear-discriminant-analysis-is-sensitive-to-cross-validation-lda-overfit-p/306729


##### Implementation

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.data",sep=",",names=["Sepal_length","Sepal_Width","Petal_length","Petal_Width","Class"])
df.tail()

Sepal_length  Sepal_Width  Petal_length  Petal_Width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [9]:
from sklearn.preprocessing import LabelEncoder

X = df.iloc[:,0:4]
y = df['Class'].values

encoder = LabelEncoder()
y_label = encoder.fit(y)
y_encoded = y_label.transform(y)+1

label_dict = {1: 'Setosa', 2: 'Versicolor', 3:'Virginica'}

##### feature selection approaches

1. filter method (manual selection by evalutaing using the metrics like fisher score, chi-square, correlation coefficient etc)

2. wrapper method (use algorithm such has subset selection)

3. Embedded method (use L1 or L2 regularization)

referenced from

https://sebastianraschka.com/faq/docs/feature_sele_categories.html

LDA for classifier requires normally distributed data and identical covariance matrices for every class, however LDA will still work well for dimension reduction regardless of the above

##### Steps

This looks same as PCA

1. find the mean of all the classes
2. find the scatter matrix


In [3]:
#find the mean

np.set_printoptions(precision=4)

all_mean = []
for i in range(1,4):
    all_mean.append(np.mean(X[y_encoded==i] , axis=0))    

In [4]:
all_mean

[Sepal_length    5.006
 Sepal_Width     3.418
 Petal_length    1.464
 Petal_Width     0.244
 dtype: float64, Sepal_length    5.936
 Sepal_Width     2.770
 Petal_length    4.260
 Petal_Width     1.326
 dtype: float64, Sepal_length    6.588
 Sepal_Width     2.974
 Petal_length    5.552
 Petal_Width     2.026
 dtype: float64]

In [36]:
#within class scatter matrix 

scatter_matrix = np.zeros((4,4))
for cl,mv in zip(range(1,4), all_mean):
    class_sc_mat = np.zeros((4,4))                  # scatter matrix for every class
    df2 = X[y_encoded == cl]
    for i,j in df2.iterrows():
        row = np.array([j["Sepal_length"],j["Sepal_Width"],j["Petal_length"],j["Petal_Width"]])
        print(type(row),type(mv))
        row, mv = row.reshape(4,1), mv.reshape(4,1) # make column vectors
        class_sc_mat += (row-mv).dot((row-mv).T)
    scatter_matrix += class_sc_mat                             # sum class scatter matrices
scatter_matrix


<class 'numpy.ndarray'> <class 'pandas.core.series.Series'>


AttributeError: 'Series' object has no attribute 'reshape'

In [32]:
df2 = X[y_encoded == 1]
for i,j in df2.iterrows():
    print(np.array([j["Sepal_length"],j["Sepal_Width"],j["Petal_length"],j["Petal_Width"]]))


[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.1 1.5 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]


##### The implementation has been taken from 

https://sebastianraschka.com/Articles/2014_python_lda.html

###### Detour 

why is it required that the residuals are normally distributed for Linear Regression ?

this is needed because this means for different values of the input the model is consistently giving the output, if this is not true then this means that the model is selecting giving values to one type of input over other.

the amount of error in your model is consistent across the full range of your observed data.

https://www.researchgate.net/post/Why_do_the_residuals_need_to_be_normal_when_carrying_out_multi_level_modeling
https://stats.stackexchange.com/questions/12262/what-if-residuals-are-normally-distributed-but-y-is-not

we can use f string in python, which is cool. Checkout below

In [ ]:
name = "Manjit"
text = f"Hello {name}" #just write f next to the string and then use the variable name
text